# Generated by Django 5.2.17 on 2026-08-13 23:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0012_sales_document_postal_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_code', models.CharField(max_length=50)),
                ('external_message_id', models.CharField(max_length=160)),
                ('sender_normalized', models.CharField(db_index=True, max_length=20)),
                ('recipient_normalized', models.CharField(db_index=True, max_length=20)),
                ('provider_received_at', models.DateTimeField(db_index=True)),
                ('system_received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound')], default='inbound', editable=False, max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('body_retention_policy', models.CharField(choices=[('not_retained', 'Not retained')], default='not_retained', editable=False, max_length=24)),
                ('processing_state', models.CharField(choices=[('unmatched', 'Unmatched'), ('linked', 'Linked')], db_index=True, default='unmatched', max_length=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_sms_messages', to='sales.customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_sms_messages', to='sales.lead')),
            ],
            options={
                'ordering': ['-provider_received_at', '-id'],
                'indexes': [models.Index(fields=['provider_code', '-provider_received_at'], name='communicati_provide_128a0b_idx'), models.Index(fields=['recipient_normalized', '-provider_received_at'], name='communicati_recipie_9d5df6_idx'), models.Index(fields=['customer', '-provider_received_at'], name='communicati_custome_74283d_idx'), models.Index(fields=['lead', '-provider_received_at'], name='communicati_lead_id_efd673_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider_code', 'external_message_id'), name='uniq_inbound_sms_provider_message'), models.CheckConstraint(condition=models.Q(('provider_code__regex', '\\A[a-z0-9][a-z0-9_-]{0,49}\\Z')), name='inbound_sms_provider_code_shape'), models.CheckConstraint(condition=models.Q(('external_message_id__regex', '\\S')), name='inbound_sms_external_id_nonblank'), models.CheckConstraint(condition=models.Q(('sender_normalized__regex', '\\A\\+[1-9][0-9]{7,14}\\Z')), name='inbound_sms_sender_e164'), models.CheckConstraint(condition=models.Q(('recipient_normalized__regex', '\\A\\+[1-9][0-9]{7,14}\\Z')), name='inbound_sms_recipient_e164'), models.CheckConstraint(condition=models.Q(('direction', 'inbound')), name='inbound_sms_direction_only'), models.CheckConstraint(condition=models.Q(('body_retention_policy', 'not_retained')), name='inbound_sms_body_not_retained'), models.CheckConstraint(condition=models.Q(('processing_state__in', ['unmatched', 'linked'])), name='inbound_sms_processing_state_valid'), models.CheckConstraint(condition=models.Q(('lead__isnull', True), ('customer__isnull', False), _connector='OR'), name='inbound_sms_lead_requires_customer')],
            },
        ),
    ]
