# Generated by Django 5.2.17 on 2026-09-03 13:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        ('sales', '0019_customer_economic_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_code', models.CharField(max_length=50)),
                ('recipient_normalized', models.CharField(db_index=True, max_length=20)),
                ('body_text', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], db_index=True, max_length=20)),
                ('status_detail', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbound_sms_messages', to='sales.customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbound_sms_messages', to='sales.lead')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at', '-id'],
                'indexes': [models.Index(fields=['customer', '-sent_at'], name='communicati_custome_27ab1e_idx'), models.Index(fields=['lead', '-sent_at'], name='communicati_lead_id_cf15c2_idx'), models.Index(fields=['status', '-sent_at'], name='communicati_status_c948f9_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('provider_code__regex', '\\A[a-z0-9][a-z0-9_-]{0,49}\\Z')), name='outbound_sms_provider_code_shape'), models.CheckConstraint(condition=models.Q(('recipient_normalized__regex', '\\A\\+[1-9][0-9]{7,14}\\Z')), name='outbound_sms_recipient_e164'), models.CheckConstraint(condition=models.Q(('body_text__regex', '\\S')), name='outbound_sms_body_nonblank'), models.CheckConstraint(condition=models.Q(('status__in', ['sent', 'failed'])), name='outbound_sms_status_valid'), models.CheckConstraint(condition=models.Q(('lead__isnull', True), ('customer__isnull', False), _connector='OR'), name='outbound_sms_lead_requires_customer')],
            },
        ),
    ]
