# Generated by Django 5.2.17 on 2026-09-08 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_outboundsms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsProviderSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('auth_mode', models.CharField(choices=[('api_key', 'کلید ثابت (هدر/بدنه)'), ('oauth2_password', 'OAuth2 (نام\u200cکاربری و رمز عبور)')], default='api_key', max_length=20)),
                ('recipient_number_style', models.CharField(choices=[('e164', '+۹۸۹۱۲xxxxxxx (بدون تغییر)'), ('digits_only', '۹۸۹۱۲xxxxxxx (بدون +)'), ('local_zero', '۰۹۱۲xxxxxxx (صفر ابتدایی)')], default='e164', max_length=20)),
                ('send_url', models.CharField(blank=True, max_length=500)),
                ('body_template', models.TextField(blank=True)),
                ('headers', models.TextField(blank=True)),
                ('sender_id', models.CharField(blank=True, max_length=32)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=10)),
                ('token_url', models.CharField(blank=True, max_length=500)),
                ('token_username', models.CharField(blank=True, max_length=255)),
                ('token_password', models.CharField(blank=True, max_length=255)),
                ('token_extra_params', models.TextField(blank=True)),
                ('test_url', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('auth_mode__in', ['api_key', 'oauth2_password'])), name='sms_provider_settings_auth_mode_valid'), models.CheckConstraint(condition=models.Q(('recipient_number_style__in', ['e164', 'digits_only', 'local_zero'])), name='sms_provider_settings_number_style_valid')],
            },
        ),
    ]
