# Generated by Django 5.2.17 on 2026-09-09 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_smsprovidersettings'),
        ('sales', '0019_customer_economic_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body_text', models.TextField()),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sending', 'Sending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_for', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SmsCampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_normalized', models.CharField(db_index=True, max_length=20)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='communications.smscampaign')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sms_campaign_recipients', to='sales.customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sms_campaign_recipients', to='sales.lead')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_recipients', to='communications.outboundsms')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('body_text', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='smscampaign',
            index=models.Index(fields=['status', 'scheduled_for'], name='communicati_status_89406b_idx'),
        ),
        migrations.AddConstraint(
            model_name='smscampaign',
            constraint=models.CheckConstraint(condition=models.Q(('body_text__regex', '\\S')), name='sms_campaign_body_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='smscampaign',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['scheduled', 'sending', 'completed', 'cancelled'])), name='sms_campaign_status_valid'),
        ),
        migrations.AddIndex(
            model_name='smscampaignrecipient',
            index=models.Index(fields=['campaign', 'state'], name='communicati_campaig_df2f56_idx'),
        ),
        migrations.AddConstraint(
            model_name='smscampaignrecipient',
            constraint=models.CheckConstraint(condition=models.Q(('recipient_normalized__regex', '\\A\\+[1-9][0-9]{7,14}\\Z')), name='sms_campaign_recipient_e164'),
        ),
        migrations.AddConstraint(
            model_name='smscampaignrecipient',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['pending', 'sent', 'failed'])), name='sms_campaign_recipient_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='smscampaignrecipient',
            constraint=models.CheckConstraint(condition=models.Q(('lead__isnull', True), ('customer__isnull', False), _connector='OR'), name='sms_campaign_recipient_lead_requires_customer'),
        ),
        migrations.AddConstraint(
            model_name='smscampaignrecipient',
            constraint=models.UniqueConstraint(fields=('campaign', 'recipient_normalized'), name='sms_campaign_recipient_unique_per_campaign'),
        ),
        migrations.AddConstraint(
            model_name='smstemplate',
            constraint=models.CheckConstraint(condition=models.Q(('title__regex', '\\S')), name='sms_template_title_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='smstemplate',
            constraint=models.CheckConstraint(condition=models.Q(('body_text__regex', '\\S')), name='sms_template_body_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='smstemplate',
            constraint=models.UniqueConstraint(fields=('title',), name='sms_template_title_unique'),
        ),
    ]
