# Generated by Django 5.2.17 on 2026-08-15 21:58

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('inventory', '0001_initial'),
        ('sales', '0013_product_barcode_product_brand_productcategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='installment_plan', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='sales.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='sales.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales.lead'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='billing.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='sales.product'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cheque',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cheque', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payment_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='sales.customer'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='sales.lead'),
        ),
        migrations.AddField(
            model_name='order',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='billing.quotation'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.quotation'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='sales.product'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='billing.quotation'),
        ),
        migrations.AddIndex(
            model_name='chequestatushistory',
            index=models.Index(fields=['cheque', '-changed_at'], name='billing_che_cheque__a74b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='customerledgerentry',
            index=models.Index(fields=['customer', '-occurred_at', '-id'], name='billing_cus_custome_c47746_idx'),
        ),
        migrations.AddIndex(
            model_name='customerledgerentry',
            index=models.Index(fields=['reference_kind', 'reference_id'], name='billing_cus_referen_472694_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0)), name='ledger_debit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customerledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('credit__gte', 0)), name='ledger_credit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customerledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit__gt', 0), ('credit', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='ledger_exactly_one_side'),
        ),
        migrations.AddConstraint(
            model_name='customerledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('entry_type__in', ['opening_balance', 'invoice_issued', 'invoice_cancelled', 'payment_received', 'payment_cancelled', 'adjustment_debit', 'adjustment_credit'])), name='ledger_entry_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='customerledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reference_id__isnull', True), ('reference_kind', 'none')), models.Q(models.Q(('reference_kind', 'none'), _negated=True), ('reference_id__isnull', False)), _connector='OR'), name='ledger_reference_pair'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['status', 'due_date'], name='billing_ins_status_9a6d1e_idx'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.UniqueConstraint(fields=('plan', 'sequence'), name='uniq_installment_plan_sequence'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='installment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='installment_paid_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__lte', models.F('amount'))), name='installment_paid_within_amount'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'partially_paid', 'paid', 'cancelled'])), name='installment_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='installmentplan',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='installment_plan_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='installmentplan',
            constraint=models.CheckConstraint(condition=models.Q(('installment_count__gte', 1), ('installment_count__lte', 120)), name='installment_plan_count_bounded'),
        ),
        migrations.AddConstraint(
            model_name='installmentplan',
            constraint=models.CheckConstraint(condition=models.Q(('interval_days__gte', 1), ('interval_days__lte', 365)), name='installment_plan_interval_bounded'),
        ),
        migrations.AddConstraint(
            model_name='installmentplan',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'completed', 'cancelled'])), name='installment_plan_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='invoice_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='invoice_item_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='invoice_item_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='invoice_item_discount_percent_bounded'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='invoice_item_line_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('unit_price'), '*', models.F('quantity')), '-', models.F('discount_amount')))), name='invoice_item_line_total_matches_inputs'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.UniqueConstraint(fields=('invoice', 'line_number'), name='uniq_invoice_item_line_number'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost_snapshot__isnull', True), ('unit_cost_snapshot__gte', 0), _connector='OR'), name='invoice_item_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='order_item_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='order_item_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='order_item_discount_percent_bounded'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='order_item_line_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('unit_price'), '*', models.F('quantity')), '-', models.F('discount_amount')))), name='order_item_line_total_matches_inputs'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'line_number'), name='uniq_order_item_line_number'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', '-received_at'], name='billing_pay_custome_6ec67a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-received_at'], name='billing_pay_status_a72995_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('number__regex', '\\S')), name='payment_number_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_amount__gte', 0)), name='payment_allocated_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_amount__lte', models.F('amount'))), name='payment_allocated_within_amount'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('method__in', ['cash', 'card', 'bank_transfer', 'cheque'])), name='payment_method_valid'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'confirmed', 'cancelled'])), name='payment_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='uniq_payment_idempotency_key'),
        ),
        migrations.AddIndex(
            model_name='cheque',
            index=models.Index(fields=['status', 'due_date'], name='billing_che_status_d8fcd1_idx'),
        ),
        migrations.AddConstraint(
            model_name='cheque',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='cheque_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='cheque',
            constraint=models.CheckConstraint(condition=models.Q(('bank_name__regex', '\\S')), name='cheque_bank_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='cheque',
            constraint=models.CheckConstraint(condition=models.Q(('serial_number__regex', '\\S')), name='cheque_serial_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='cheque',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['registered', 'deposited', 'cleared', 'bounced', 'returned', 'cancelled'])), name='cheque_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='cheque',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('bank_name', 'serial_number'), name='uniq_active_cheque_bank_serial'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['invoice', '-created_at'], name='billing_pay_invoice_b3c555_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['payment', '-created_at'], name='billing_pay_payment_68ebab_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_allocation_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reversed', False)), fields=('payment', 'invoice'), name='uniq_active_payment_invoice_allocation'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['customer', '-created_at'], name='billing_quo_custome_810a55_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['status', '-created_at'], name='billing_quo_status_446507_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['created_by', '-created_at'], name='billing_quo_created_1ff521_idx'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.CheckConstraint(condition=models.Q(('number__regex', '\\S')), name='quotation_number_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'sent', 'accepted', 'rejected', 'expired', 'cancelled'])), name='quotation_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_amount__gte', 0)), name='quotation_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='quotation_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)), name='quotation_tax_rate_bounded'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='quotation_tax_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='quotation_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__lte', models.F('subtotal_amount'))), name='quotation_discount_within_subtotal'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('subtotal_amount'), '-', models.F('discount_amount')), '+', models.F('tax_amount')))), name='quotation_total_matches_parts'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='billing_ord_custome_382e61_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='billing_ord_status_7e005a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_by', '-created_at'], name='billing_ord_created_823bd9_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('number__regex', '\\S')), name='order_number_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'confirmed', 'fulfilled', 'cancelled'])), name='order_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_amount__gte', 0)), name='order_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='order_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)), name='order_tax_rate_bounded'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='order_tax_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='order_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__lte', models.F('subtotal_amount'))), name='order_discount_within_subtotal'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('subtotal_amount'), '-', models.F('discount_amount')), '+', models.F('tax_amount')))), name='order_total_matches_parts'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', '-created_at'], name='billing_inv_custome_4b1fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', '-issued_at'], name='billing_inv_status_32089d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['created_by', '-created_at'], name='billing_inv_created_d30b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_at'], name='billing_inv_due_at_51fb5f_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('number__regex', '\\S')), name='invoice_number_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'issued', 'cancelled'])), name='invoice_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_amount__gte', 0)), name='invoice_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='invoice_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)), name='invoice_tax_rate_bounded'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='invoice_tax_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='invoice_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__lte', models.F('subtotal_amount'))), name='invoice_discount_within_subtotal'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('subtotal_amount'), '-', models.F('discount_amount')), '+', models.F('tax_amount')))), name='invoice_total_matches_parts'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='invoice_paid_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__lte', models.F('total_amount'))), name='invoice_paid_within_total'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('issued_at__isnull', True), ('status', 'draft')), models.Q(('status', 'draft'), _negated=True), _connector='OR'), name='invoice_draft_has_no_issue_time'),
        ),
        migrations.AddConstraint(
            model_name='quotationitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quotation_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='quotationitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='quotation_item_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='quotationitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='quotation_item_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='quotationitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='quotation_item_discount_percent_bounded'),
        ),
        migrations.AddConstraint(
            model_name='quotationitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='quotation_item_line_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='quotationitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('unit_price'), '*', models.F('quantity')), '-', models.F('discount_amount')))), name='quotation_item_line_total_matches_inputs'),
        ),
        migrations.AddConstraint(
            model_name='quotationitem',
            constraint=models.UniqueConstraint(fields=('quotation', 'line_number'), name='uniq_quotation_item_line_number'),
        ),
    ]
