# Generated by Django 5.2.17 on 2026-08-18 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        ('inventory', '0001_initial'),
        ('sales', '0015_remove_targetaudiencemember_uniq_target_member_per_lead_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='manual_paid_entry',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='manual_settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='manual_settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manually_settled_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('manual_paid_entry__isnull', True), ('manual_paid_entry__gte', 0), _connector='OR'), name='invoice_manual_entry_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('manual_settled_at__isnull', True), ('manual_settled_by__isnull', True)), models.Q(('manual_settled_at__isnull', False), ('manual_settled_by__isnull', False)), _connector='OR'), name='invoice_manual_settlement_fields_consistent'),
        ),
    ]
