# Generated by Django 5.2.17 on 2026-08-18 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_order_stock_applied_order_stock_revision_and_more'),
        ('inventory', '0001_initial'),
        ('sales', '0015_remove_targetaudiencemember_uniq_target_member_per_lead_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('post', 'پست'), ('courier', 'پیک')], default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('shipping_method__in', ['', 'post', 'courier'])), name='order_shipping_method_valid'),
        ),
    ]
