# Generated by Django 5.2.17 on 2026-08-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_order_shipping_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('unofficial', 'غیررسمی'), ('official', 'رسمی')], db_index=True, default='unofficial', max_length=20),
        ),
    ]
