# Generated by Django 5.2.17 on 2026-08-26 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_invoice_invoice_type'),
        ('inventory', '0001_initial'),
        ('sales', '0019_customer_economic_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='official_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('official_number', ''), _negated=True), fields=('official_number',), name='invoice_official_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('official_number', ''), ('invoice_type', 'official'), _connector='OR'), name='invoice_official_number_requires_official_type'),
        ),
    ]
