# Generated by Django 5.2.17 on 2026-08-26 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_payment_bank_account_payment_bank_name_and_more'),
        ('sales', '0019_customer_economic_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='bank_account',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='cheque',
            name='paid_to',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cheque',
            name='source',
            field=models.CharField(blank=True, choices=[('own', 'چک خودمان'), ('customer_endorsed', 'چک مشتری')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='direction',
            field=models.CharField(choices=[('receipt', 'دریافتی'), ('disbursement', 'پرداختی')], db_index=True, default='receipt', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payee',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('deposited', 'Deposited'), ('cleared', 'Cleared'), ('bounced', 'Bounced'), ('returned', 'Returned to customer'), ('cancelled', 'Cancelled'), ('spent', 'Spent')], db_index=True, default='registered', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('opening_balance', 'Opening balance'), ('invoice_issued', 'Invoice issued'), ('invoice_cancelled', 'Invoice cancelled'), ('payment_received', 'Payment received'), ('payment_made', 'Payment made'), ('payment_cancelled', 'Payment cancelled'), ('adjustment_debit', 'Adjustment (debit)'), ('adjustment_credit', 'Adjustment (credit)')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.customer'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('direction__in', ['receipt', 'disbursement'])), name='payment_direction_valid'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('direction', 'disbursement'), ('customer__isnull', False), _connector='OR'), name='payment_receipt_requires_customer'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('direction', 'receipt'), models.Q(('payee', ''), _negated=True), _connector='OR'), name='payment_disbursement_requires_payee'),
        ),
    ]
