# Generated by Django 5.2.17 on 2026-08-26 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_cheque_bank_account_cheque_paid_to_cheque_source_and_more'),
        ('sales', '0019_customer_economic_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cheque',
            name='cheque_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='customerledgerentry',
            name='ledger_entry_type_valid',
        ),
        migrations.AddConstraint(
            model_name='cheque',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['registered', 'deposited', 'cleared', 'bounced', 'returned', 'cancelled', 'spent'])), name='cheque_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='customerledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('entry_type__in', ['opening_balance', 'invoice_issued', 'invoice_cancelled', 'payment_received', 'payment_made', 'payment_cancelled', 'adjustment_debit', 'adjustment_credit'])), name='ledger_entry_type_valid'),
        ),
    ]
