# Generated by Django 5.2.17 on 2026-08-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_remove_cheque_cheque_status_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='buyer_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_economic_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_national_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_postal_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_economic_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_national_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_postal_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_registration_number',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
