# Generated by Django 5.2.17 on 2026-08-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_invoice_buyer_address_invoice_buyer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='document_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
