# Generated by Django 5.2.17 on 2026-09-28 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_installment_plan_down_payment_and_profit_rate'),
        ('inventory', '0001_initial'),
        ('sales', '0024_backfill_interaction_normalized_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__isnull', True), models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), _connector='OR'), name='invoice_discount_percent_bounded'),
        ),
    ]
