# Generated by Django 5.2.17 on 2026-09-29 10:55

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_invoice_discount_percent'),
        ('inventory', '0001_initial'),
        ('sales', '0025_postal_shipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='installment_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='installment_down_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='invoice',
            name='installment_first_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='installment_interval_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'نقدی'), ('installment', 'اقساط')], db_index=True, default='cash', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('payment_type', 'cash'), models.Q(('payment_type', 'installment'), ('installment_count__gte', 1), ('installment_count__lte', 120), ('installment_first_due__isnull', False), ('installment_interval_days__gte', 1), ('installment_interval_days__lte', 365), ('installment_down_payment__gte', 0)), _connector='OR'), name='invoice_installment_terms_valid'),
        ),
    ]
