"""Let one receipt be allocated to the same invoice more than once.

Expand-only in effect: it relaxes a rule, so the previous release's code runs
against this schema unchanged. Reversing it would re-add the uniqueness, which
fails as soon as a repeated allocation exists — roll back by redeploying the
previous version, not by migrating backwards.
"""
# Generated by Django 5.2.17 on 2026-10-02 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_invoice_payment_type_and_installment_terms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentallocation',
            name='uniq_active_payment_invoice_allocation',
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['payment', 'invoice'], name='payalloc_payment_invoice_idx'),
        ),
    ]
