# Generated by Django 5.2.17 on 2026-10-02 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_payment_allocation_repeatable'),
        ('inventory', '0001_initial'),
        ('sales', '0029_campaigns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_requests', to='billing.invoice'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice__isnull', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('invoice',), name='uniq_active_fulfillment_per_invoice'),
        ),
    ]
