# Generated by Django 5.2.17 on 2026-10-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_order_fulfillment_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='batch_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
