# Generated by Django 5.2.17 on 2026-10-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_order_batch_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentallocation',
            name='release_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='request_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
