# Generated by Django 5.2.17 on 2026-10-04 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_allocation_release_reason_request_key'),
        ('sales', '0031_campaign_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intended_invoices', to='sales.campaign'),
        ),
    ]
