# Generated by Django 5.2.17 on 2026-09-27 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(max_length=32)),
                ('person_id', models.PositiveBigIntegerField()),
                ('body', models.CharField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'person note',
                'verbose_name_plural': 'person notes',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['person_type', 'person_id', '-created_at'], name='person_note_recent')],
                'constraints': [models.CheckConstraint(condition=models.Q(('body__regex', '\\S')), name='person_note_body_nonblank')],
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(max_length=32)),
                ('person_id', models.PositiveBigIntegerField()),
                ('kind', models.CharField(max_length=40)),
                ('occurred_at', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.CharField(blank=True, max_length=4000)),
                ('source', models.CharField(max_length=40)),
                ('source_ref', models.CharField(blank=True, max_length=64)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('required_capability', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'timeline entry',
                'verbose_name_plural': 'timeline entries',
                'indexes': [models.Index(fields=['person_type', 'person_id', '-occurred_at'], name='timeline_person_recent')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_ref', ''), _negated=True), fields=('source', 'source_ref', 'kind'), name='timeline_entry_source_unique'), models.CheckConstraint(condition=models.Q(('title__regex', '\\S')), name='timeline_entry_title_nonblank')],
            },
        ),
    ]
