# Generated by Django 5.2.17 on 2026-08-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentProfileCache',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('profile_id', models.CharField(max_length=64)),
                ('manifest_fingerprint', models.CharField(blank=True, max_length=64)),
                ('features', models.JSONField(default=list)),
                ('source', models.CharField(max_length=32)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('singleton', 1)), name='common_deploymentprofilecache_is_singleton')],
            },
        ),
    ]
