# Generated by Django 5.2.17 on 2026-09-03 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('logo_content', models.BinaryField(blank=True, null=True)),
                ('logo_content_type', models.CharField(blank=True, max_length=32)),
                ('logo_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('logo_original_filename', models.CharField(blank=True, max_length=255)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('singleton', 1)), name='common_brandsettings_is_singleton'), models.CheckConstraint(condition=models.Q(models.Q(('logo_content__isnull', True), ('logo_content_type', ''), ('logo_size_bytes__isnull', True)), models.Q(('logo_content__isnull', False), ('logo_content_type__in', ('image/jpeg', 'image/png', 'image/webp')), ('logo_size_bytes__isnull', False)), _connector='OR'), name='common_brandsettings_logo_all_or_nothing')],
            },
        ),
    ]
