# Generated by Django 5.2.17 on 2026-09-09 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_brandsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('hidden_widgets', models.JSONField(blank=True, default=list)),
                ('widget_order', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.AddField(
            model_name='brandsettings',
            name='accent_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddConstraint(
            model_name='brandsettings',
            constraint=models.CheckConstraint(condition=models.Q(('accent_color', ''), ('accent_color__regex', '\\A#[0-9a-f]{6}\\Z'), _connector='OR'), name='common_brandsettings_accent_color_shape'),
        ),
        migrations.AddField(
            model_name='dashboardsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='dashboardsettings',
            constraint=models.CheckConstraint(condition=models.Q(('singleton', 1)), name='common_dashboardsettings_is_singleton'),
        ),
    ]
