# Generated by Django 5.2.17 on 2026-09-20 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usercapabilityoverride'),
        ('common', '0003_dashboardsettings_and_brandsettings_accent_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDashboardLayout',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dashboard_layout', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hidden_widgets', models.JSONField(blank=True, default=list)),
                ('widget_order', models.JSONField(blank=True, default=list)),
                ('widget_sizes', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='panel_preference', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('font_family', models.CharField(choices=[('iransans', 'ایران\u200cسنس (پیش\u200cفرض)'), ('tahoma', 'تاهوما'), ('nazanin', 'بی\u200cنازنین'), ('mitra', 'بی\u200cمیترا'), ('system', 'قلم سیستم')], default='iransans', max_length=16)),
                ('font_scale', models.CharField(choices=[('sm', 'کوچک'), ('md', 'متوسط (پیش\u200cفرض)'), ('lg', 'بزرگ'), ('xl', 'خیلی بزرگ')], default='md', max_length=2)),
                ('currency_unit', models.CharField(choices=[('rial', 'ریال'), ('toman', 'تومان')], default='rial', max_length=8)),
                ('theme', models.CharField(choices=[('system', 'هماهنگ با سیستم'), ('light', 'روشن'), ('dark', 'تیره')], default='system', max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
