# Generated by Django 5.2.17 on 2026-09-20 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_userdashboardlayout_userpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=32, unique=True)),
                ('kind', models.CharField(choices=[('backup', 'پشتیبان\u200cگیری'), ('restore', 'بازگردانی')], max_length=8)),
                ('status', models.CharField(choices=[('waiting', 'در صف اجرا'), ('done', 'انجام شد'), ('failed', 'ناموفق'), ('expired', 'منقضی شد')], default='waiting', max_length=8)),
                ('original_filename', models.CharField(blank=True, max_length=120)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('archive_name', models.CharField(blank=True, max_length=128)),
                ('message', models.TextField(blank=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['-created_at'], name='backupjob_created_idx')],
            },
        ),
    ]
