# Generated by Django 5.2.17 on 2026-09-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_panel_font_family_bundled_faces'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='note',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
