# Generated by Django 5.2.17 on 2026-10-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_backupjob_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboardlayout',
            name='widget_positions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
