# Generated by Django 5.2.17 on 2026-10-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_dashboard_widget_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboardlayout',
            name='shown_widgets',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
