# Generated by Django 5.2.17 on 2026-10-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_user_dashboard_shown_widgets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='font_family',
            field=models.CharField(choices=[('vazirmatn', 'وزیرمتن (پیش\u200cفرض)'), ('iransans', 'ایران\u200cسنس'), ('estedad', 'استعداد'), ('sahel', 'ساحل'), ('shabnam', 'شبنم'), ('samim', 'صمیم'), ('parastoo', 'پرستو'), ('tahoma', 'تاهوما'), ('nazanin', 'بی\u200cنازنین'), ('mitra', 'بی\u200cمیترا'), ('system', 'قلم سیستم')], default='vazirmatn', max_length=16),
        ),
    ]
