# Generated by Django 5.2.17 on 2026-08-12 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0012_sales_document_postal_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSalesRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=4000)),
                ('status', models.CharField(db_index=True, max_length=80)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_after_sales_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_after_sales_requests', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='after_sales_requests', to='sales.customer')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='after_sales_requests', to='sales.salesdocument')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='after_sales_requests', to='sales.sale')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AfterSalesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('status_changed', 'Status changed'), ('closed', 'Closed')], max_length=32)),
                ('from_status', models.CharField(blank=True, max_length=80)),
                ('to_status', models.CharField(blank=True, max_length=80)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='after_sales_changes', to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='after_sales_assignments_lost', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='after_sales_assignments_received', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='aftersales.aftersalesrequest')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='aftersalesrequest',
            index=models.Index(fields=['assigned_to', 'status', '-created_at'], name='aftersales__assigne_bda6d8_idx'),
        ),
        migrations.AddIndex(
            model_name='aftersalesrequest',
            index=models.Index(fields=['customer', '-created_at'], name='aftersales__custome_9b72eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='aftersalesrequest',
            constraint=models.CheckConstraint(condition=models.Q(('subject__regex', '\\S')), name='after_sales_subject_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='aftersalesrequest',
            constraint=models.CheckConstraint(condition=models.Q(('description__regex', '\\S')), name='after_sales_description_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='aftersalesrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__regex', '\\S')), name='after_sales_status_nonblank'),
        ),
        migrations.AddIndex(
            model_name='aftersaleshistory',
            index=models.Index(fields=['request', '-created_at'], name='aftersales__request_f614c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='aftersaleshistory',
            constraint=models.CheckConstraint(condition=models.Q(('event__in', ['created', 'assigned', 'status_changed', 'closed'])), name='after_sales_history_event_valid'),
        ),
    ]
