# Generated by Django 5.2.17 on 2026-09-03 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aftersales', '0001_after_sales_foundation'),
        ('sales', '0019_customer_economic_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aftersaleshistory',
            name='after_sales_history_event_valid',
        ),
        migrations.AddField(
            model_name='aftersaleshistory',
            name='appointment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aftersalesrequest',
            name='next_appointment_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='aftersaleshistory',
            name='event',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('status_changed', 'Status changed'), ('closed', 'Closed'), ('appointment_scheduled', 'Appointment scheduled')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='aftersalesrequest',
            index=models.Index(fields=['assigned_to', 'next_appointment_at'], name='aftersales__assigne_6bc121_idx'),
        ),
        migrations.AddConstraint(
            model_name='aftersaleshistory',
            constraint=models.CheckConstraint(condition=models.Q(('event__in', ['created', 'assigned', 'status_changed', 'closed', 'appointment_scheduled'])), name='after_sales_history_event_valid'),
        ),
    ]
