# Generated by Django 5.2.17 on 2026-08-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(role__in=["sales_agent", "sales_manager", "company_it", "platform_admin"]),
                name="accounts_user_role_valid",
            ),
        ),
    ]
