# Generated by Django 5.2.17 on 2026-08-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role_constraint'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workstream',
            field=models.CharField(choices=[('sales', 'Sales'), ('after_sales', 'After Sales')], db_index=True, default='sales', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('workstream__in', ['sales', 'after_sales'])), name='accounts_user_workstream_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role', 'sales_agent'), ('workstream', 'sales'), _connector='OR'), name='accounts_user_elevated_workstream_sales'),
        ),
    ]
