# Generated by Django 5.2.17 on 2026-08-31 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_after_sales_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCapabilityOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(max_length=64)),
                ('granted', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user capability override',
                'verbose_name_plural': 'user capability overrides',
                'constraints': [models.UniqueConstraint(fields=('user', 'capability'), name='accounts_capability_override_unique')],
            },
        ),
    ]
