# Generated by Django 5.2.17 on 2026-09-20 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usercapabilityoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='avatar', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('content', models.BinaryField()),
                ('content_type', models.CharField(max_length=32)),
                ('size_bytes', models.PositiveIntegerField()),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user avatar',
                'verbose_name_plural': 'user avatars',
                'constraints': [models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='accounts_user_avatar_has_content'), models.CheckConstraint(condition=models.Q(('content_type__in', ('image/jpeg', 'image/png', 'image/webp'))), name='accounts_user_avatar_content_type_allowed')],
            },
        ),
    ]
