# Generated by Django 5.2.17 on 2026-09-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useravatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chosen_default_avatar',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
