# Generated by Django 5.2.17 on 2026-08-15 21:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0013_product_barcode_product_brand_productcategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('normalized_name', models.CharField(editable=False, max_length=120, unique=True)),
                ('address', models.CharField(blank=True, max_length=2000)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_warehouses', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('opening', 'Opening stock'), ('purchase', 'Purchase receipt'), ('sale', 'Sale issue'), ('return_in', 'Customer return'), ('return_out', 'Return to supplier'), ('adjustment_in', 'Adjustment increase'), ('adjustment_out', 'Adjustment decrease'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out')], db_index=True, max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('resulting_quantity', models.IntegerField()),
                ('resulting_average_cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference_kind', models.CharField(choices=[('manual', 'Manual entry'), ('invoice', 'Invoice'), ('order', 'Order'), ('transfer', 'Warehouse transfer')], default='manual', max_length=20)),
                ('reference_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=64)),
                ('idempotency_key', models.CharField(blank=True, max_length=64)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('notes', models.CharField(blank=True, max_length=2000)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='sales.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
                ('average_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('last_movement_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='sales.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['warehouse_id', 'product_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '\\A[a-z0-9][a-z0-9_-]{0,63}\\Z')), name='warehouse_code_shape'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='warehouse_name_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_name__regex', '\\S')), name='warehouse_normalized_name_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='uniq_single_default_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.CheckConstraint(condition=models.Q(('is_default', False), ('is_active', True), _connector='OR'), name='warehouse_default_is_active'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['warehouse', 'product', '-occurred_at'], name='inventory_s_warehou_658112_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', '-occurred_at'], name='inventory_s_product_5ccbf2_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_kind', 'reference_id'], name='inventory_s_referen_bdda90_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_movement_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__isnull', True), ('unit_cost__gte', 0), _connector='OR'), name='stock_movement_unit_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('resulting_average_cost__gte', 0)), name='stock_movement_resulting_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('movement_type__in', ['opening', 'purchase', 'sale', 'return_in', 'return_out', 'adjustment_in', 'adjustment_out', 'transfer_in', 'transfer_out'])), name='stock_movement_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('reference_kind__in', ['manual', 'invoice', 'order', 'transfer'])), name='stock_movement_reference_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reference_id__isnull', True), ('reference_kind', 'manual')), models.Q(models.Q(('reference_kind', 'manual'), _negated=True), ('reference_id__isnull', False)), _connector='OR'), name='stock_movement_reference_pair'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='uniq_stock_movement_idempotency_key'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['product', 'warehouse'], name='inventory_s_product_e2964c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['warehouse', 'quantity'], name='inventory_s_warehou_f597d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(fields=('warehouse', 'product'), name='uniq_stock_item_warehouse_product'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(('average_cost__gte', 0)), name='stock_item_average_cost_non_negative'),
        ),
    ]
