# Generated by Django 5.2.17 on 2026-09-27 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.CharField(blank=True, max_length=2000)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('person_type', models.CharField(blank=True, max_length=32)),
                ('person_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'باز'), ('done', 'انجام\u200cشده'), ('cancelled', 'لغوشده')], default='open', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'دستی'), ('missed_call', 'تماس بی\u200cپاسخ'), ('system', 'سامانه')], default='manual', max_length=20)),
                ('source_ref', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'due_at', 'id'],
                'indexes': [models.Index(fields=['assignee', 'status', 'due_at'], name='task_assignee_open_due'), models.Index(fields=['person_type', 'person_id', 'status'], name='task_person_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['open', 'done', 'cancelled'])), name='task_status_valid'), models.CheckConstraint(condition=models.Q(('source__in', ['manual', 'missed_call', 'system'])), name='task_source_valid'), models.CheckConstraint(condition=models.Q(('title__regex', '\\S')), name='task_title_nonblank'), models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'done')), models.Q(models.Q(('status', 'done'), _negated=True), ('completed_at__isnull', True)), _connector='OR'), name='task_completed_at_matches_status'), models.CheckConstraint(condition=models.Q(models.Q(('person_id__isnull', True), ('person_type', '')), models.Q(models.Q(('person_type', ''), _negated=True), ('person_id__isnull', False)), _connector='OR'), name='task_person_reference_complete'), models.UniqueConstraint(condition=models.Q(('source_ref', ''), _negated=True), fields=('source', 'source_ref'), name='task_source_ref_unique')],
            },
        ),
    ]
