# Generated by Django 5.2.17 on 2026-09-27 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(max_length=32)),
                ('person_id', models.PositiveBigIntegerField()),
                ('score', models.PositiveSmallIntegerField()),
                ('level', models.CharField(max_length=20)),
                ('breakdown', models.JSONField(default=list)),
                ('strategy', models.CharField(max_length=40)),
                ('computed_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'person score',
                'verbose_name_plural': 'person scores',
                'indexes': [models.Index(fields=['person_type', 'person_id', '-computed_at'], name='person_score_recent')],
                'constraints': [models.CheckConstraint(condition=models.Q(('score__lte', 100)), name='person_score_at_most_100'), models.CheckConstraint(condition=models.Q(('level__in', ['excellent', 'good', 'fair', 'weak'])), name='person_score_level_valid')],
            },
        ),
        migrations.CreateModel(
            name='ScoringSettings',
            fields=[
                ('singleton', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('customer_weights', models.JSONField(blank=True, default=dict)),
                ('user_weights', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'scoring settings',
                'verbose_name_plural': 'scoring settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('singleton', 1)), name='scoring_settings_is_singleton')],
            },
        ),
    ]
