from django.urls import path

from common.ui_views import (
    DolphinActivityLogDetailView,
    DolphinActivityLogListView,
    DolphinAfterSalesCalendarView,
    DolphinAfterSalesDetailView,
    DolphinAfterSalesListView,
    DolphinChequeListView,
    DolphinCustomerDetailView,
    DolphinCustomerLedgerView,
    DolphinCustomerListView,
    DolphinHomeView,
    DolphinInboundSMSReportView,
    DolphinInstallmentListView,
    DolphinInteractionDetailView,
    DolphinInteractionListView,
    DolphinInvoiceDetailView,
    DolphinInvoiceListView,
    DolphinInvoicePdfView,
    DolphinInvoicePrintView,
    DolphinLeadCalendarView,
    DolphinLeadDetailView,
    DolphinLeadListView,
    DolphinLoginView,
    DolphinMyProfileView,
    DolphinOrderDetailView,
    DolphinOrderListView,
    DolphinOutboundSMSView,
    DolphinPaymentDetailView,
    DolphinDisbursementListView,
    DolphinPaymentListView,
    DolphinProductCategoryDetailView,
    DolphinProductCategoryListView,
    DolphinProductDetailView,
    DolphinProductListView,
    DolphinProfitReportView,
    DolphinReceivablesReportView,
    DolphinUserProfileView,
    DolphinSaleDetailView,
    DolphinSaleListView,
    DolphinSalesDocumentDetailView,
    DolphinSalesDocumentListView,
    DolphinSalesDocumentReportView,
    DolphinStockLevelListView,
    DolphinStockMovementListView,
    DolphinStockValuationReportView,
    DolphinUserDetailView,
    DolphinUserListView,
    DolphinUserPerformanceView,
    DolphinWarehouseDetailView,
    DolphinWarehouseListView,
)


app_name = "common_ui"

urlpatterns = [
    path("login/", DolphinLoginView.as_view(), name="login"),
    path("", DolphinHomeView.as_view(), name="home"),
    path("users/", DolphinUserListView.as_view(), name="users"),
    path("users/<int:user_id>/", DolphinUserDetailView.as_view(), name="user-detail"),
    path("users/<int:user_id>/profile/", DolphinUserProfileView.as_view(), name="user-profile"),
    path("profile/", DolphinMyProfileView.as_view(), name="my-profile"),
    path("customers/", DolphinCustomerListView.as_view(), name="customers"),
    path("customers/<int:customer_id>/", DolphinCustomerDetailView.as_view(), name="customer-detail"),
    path("leads/", DolphinLeadListView.as_view(), name="leads"),
    path("leads/calendar/", DolphinLeadCalendarView.as_view(), name="lead-calendar"),
    path("leads/<int:lead_id>/", DolphinLeadDetailView.as_view(), name="lead-detail"),
    path("interactions/", DolphinInteractionListView.as_view(), name="interactions"),
    path("interactions/<int:interaction_id>/", DolphinInteractionDetailView.as_view(), name="interaction-detail"),
    path("products/", DolphinProductListView.as_view(), name="products"),
    path("products/<int:product_id>/", DolphinProductDetailView.as_view(), name="product-detail"),
    path("product-categories/", DolphinProductCategoryListView.as_view(), name="product-categories"),
    path("product-categories/<int:category_id>/", DolphinProductCategoryDetailView.as_view(), name="product-category-detail"),
    path("warehouses/", DolphinWarehouseListView.as_view(), name="warehouses"),
    path("warehouses/<int:warehouse_id>/", DolphinWarehouseDetailView.as_view(), name="warehouse-detail"),
    path("stock/", DolphinStockLevelListView.as_view(), name="stock-levels"),
    path("stock/movements/", DolphinStockMovementListView.as_view(), name="stock-movements"),
    path("sales/", DolphinSaleListView.as_view(), name="sales"),
    path("sales/<int:sale_id>/", DolphinSaleDetailView.as_view(), name="sale-detail"),
    path("orders/", DolphinOrderListView.as_view(), name="orders"),
    path("orders/<int:order_id>/", DolphinOrderDetailView.as_view(), name="order-detail"),
    path("invoices/", DolphinInvoiceListView.as_view(), name="invoices"),
    path("invoices/<int:invoice_id>/", DolphinInvoiceDetailView.as_view(), name="invoice-detail"),
    path("invoices/<int:invoice_id>/print/", DolphinInvoicePrintView.as_view(), name="invoice-print"),
    path("invoices/<int:invoice_id>/print.pdf", DolphinInvoicePdfView.as_view(), name="invoice-pdf"),
    path("payments/", DolphinPaymentListView.as_view(), name="payments"),
    path("disbursements/", DolphinDisbursementListView.as_view(), name="disbursements"),
    path("payments/<int:payment_id>/", DolphinPaymentDetailView.as_view(), name="payment-detail"),
    path("cheques/", DolphinChequeListView.as_view(), name="cheques"),
    path("installments/", DolphinInstallmentListView.as_view(), name="installments"),
    path("sales-documents/", DolphinSalesDocumentListView.as_view(), name="sales-documents"),
    path("sales-documents/<int:document_id>/", DolphinSalesDocumentDetailView.as_view(), name="sales-document-detail"),
    path("after-sales/", DolphinAfterSalesListView.as_view(), name="after-sales"),
    path("after-sales/calendar/", DolphinAfterSalesCalendarView.as_view(), name="after-sales-calendar"),
    path("after-sales/<int:request_id>/", DolphinAfterSalesDetailView.as_view(), name="after-sales-detail"),
    path("reports/user-performance/", DolphinUserPerformanceView.as_view(), name="user-performance"),
    path("reports/sales-documents/", DolphinSalesDocumentReportView.as_view(), name="sales-document-report"),
    path("reports/inbound-sms/", DolphinInboundSMSReportView.as_view(), name="inbound-sms-report"),
    path("sms/", DolphinOutboundSMSView.as_view(), name="outbound-sms"),
    path("reports/receivables/", DolphinReceivablesReportView.as_view(), name="receivables-report"),
    path("reports/profit/", DolphinProfitReportView.as_view(), name="profit-report"),
    path("reports/stock-valuation/", DolphinStockValuationReportView.as_view(), name="stock-valuation-report"),
    path("reports/customer-ledger/", DolphinCustomerLedgerView.as_view(), name="customer-ledger"),
    path("activity-logs/", DolphinActivityLogListView.as_view(), name="activity-logs"),
    path("activity-logs/<int:activity_log_id>/", DolphinActivityLogDetailView.as_view(), name="activity-log-detail"),
]
