from django.urls import path

from common.ui_views import (
    KarizActivityLogDetailView,
    KarizActivityLogListView,
    KarizAfterSalesDetailView,
    KarizAfterSalesListView,
    KarizChequeListView,
    KarizCustomerDetailView,
    KarizCustomerLedgerView,
    KarizCustomerListView,
    KarizHomeView,
    KarizInboundSMSReportView,
    KarizInstallmentListView,
    KarizInteractionDetailView,
    KarizInteractionListView,
    KarizInvoiceDetailView,
    KarizInvoiceListView,
    KarizInvoicePdfView,
    KarizInvoicePrintView,
    KarizLeadDetailView,
    KarizLeadListView,
    KarizLoginView,
    KarizOrderDetailView,
    KarizOrderListView,
    KarizPaymentDetailView,
    KarizDisbursementListView,
    KarizPaymentListView,
    KarizProductCategoryDetailView,
    KarizProductCategoryListView,
    KarizProductDetailView,
    KarizProductListView,
    KarizProfitReportView,
    KarizReceivablesReportView,
    KarizSaleDetailView,
    KarizSaleListView,
    KarizSalesDocumentDetailView,
    KarizSalesDocumentListView,
    KarizSalesDocumentReportView,
    KarizStockLevelListView,
    KarizStockMovementListView,
    KarizStockValuationReportView,
    KarizUserDetailView,
    KarizUserListView,
    KarizUserPerformanceView,
    KarizWarehouseDetailView,
    KarizWarehouseListView,
)


app_name = "common_ui"

urlpatterns = [
    path("login/", KarizLoginView.as_view(), name="login"),
    path("", KarizHomeView.as_view(), name="home"),
    path("users/", KarizUserListView.as_view(), name="users"),
    path("users/<int:user_id>/", KarizUserDetailView.as_view(), name="user-detail"),
    path("customers/", KarizCustomerListView.as_view(), name="customers"),
    path("customers/<int:customer_id>/", KarizCustomerDetailView.as_view(), name="customer-detail"),
    path("leads/", KarizLeadListView.as_view(), name="leads"),
    path("leads/<int:lead_id>/", KarizLeadDetailView.as_view(), name="lead-detail"),
    path("interactions/", KarizInteractionListView.as_view(), name="interactions"),
    path("interactions/<int:interaction_id>/", KarizInteractionDetailView.as_view(), name="interaction-detail"),
    path("products/", KarizProductListView.as_view(), name="products"),
    path("products/<int:product_id>/", KarizProductDetailView.as_view(), name="product-detail"),
    path("product-categories/", KarizProductCategoryListView.as_view(), name="product-categories"),
    path("product-categories/<int:category_id>/", KarizProductCategoryDetailView.as_view(), name="product-category-detail"),
    path("warehouses/", KarizWarehouseListView.as_view(), name="warehouses"),
    path("warehouses/<int:warehouse_id>/", KarizWarehouseDetailView.as_view(), name="warehouse-detail"),
    path("stock/", KarizStockLevelListView.as_view(), name="stock-levels"),
    path("stock/movements/", KarizStockMovementListView.as_view(), name="stock-movements"),
    path("sales/", KarizSaleListView.as_view(), name="sales"),
    path("sales/<int:sale_id>/", KarizSaleDetailView.as_view(), name="sale-detail"),
    path("orders/", KarizOrderListView.as_view(), name="orders"),
    path("orders/<int:order_id>/", KarizOrderDetailView.as_view(), name="order-detail"),
    path("invoices/", KarizInvoiceListView.as_view(), name="invoices"),
    path("invoices/<int:invoice_id>/", KarizInvoiceDetailView.as_view(), name="invoice-detail"),
    path("invoices/<int:invoice_id>/print/", KarizInvoicePrintView.as_view(), name="invoice-print"),
    path("invoices/<int:invoice_id>/print.pdf", KarizInvoicePdfView.as_view(), name="invoice-pdf"),
    path("payments/", KarizPaymentListView.as_view(), name="payments"),
    path("disbursements/", KarizDisbursementListView.as_view(), name="disbursements"),
    path("payments/<int:payment_id>/", KarizPaymentDetailView.as_view(), name="payment-detail"),
    path("cheques/", KarizChequeListView.as_view(), name="cheques"),
    path("installments/", KarizInstallmentListView.as_view(), name="installments"),
    path("sales-documents/", KarizSalesDocumentListView.as_view(), name="sales-documents"),
    path("sales-documents/<int:document_id>/", KarizSalesDocumentDetailView.as_view(), name="sales-document-detail"),
    path("after-sales/", KarizAfterSalesListView.as_view(), name="after-sales"),
    path("after-sales/<int:request_id>/", KarizAfterSalesDetailView.as_view(), name="after-sales-detail"),
    path("reports/user-performance/", KarizUserPerformanceView.as_view(), name="user-performance"),
    path("reports/sales-documents/", KarizSalesDocumentReportView.as_view(), name="sales-document-report"),
    path("reports/inbound-sms/", KarizInboundSMSReportView.as_view(), name="inbound-sms-report"),
    path("reports/receivables/", KarizReceivablesReportView.as_view(), name="receivables-report"),
    path("reports/profit/", KarizProfitReportView.as_view(), name="profit-report"),
    path("reports/stock-valuation/", KarizStockValuationReportView.as_view(), name="stock-valuation-report"),
    path("reports/customer-ledger/", KarizCustomerLedgerView.as_view(), name="customer-ledger"),
    path("activity-logs/", KarizActivityLogListView.as_view(), name="activity-logs"),
    path("activity-logs/<int:activity_log_id>/", KarizActivityLogDetailView.as_view(), name="activity-log-detail"),
]
