# Generated by Django 5.2.17 on 2026-09-27 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=60)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('person_type', models.CharField(blank=True, max_length=32)),
                ('person_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processed', 'پردازش\u200cشده'), ('failed', 'ناموفق')], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('available_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['status', 'available_at'], name='domain_event_due')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('dedupe_key',), name='domain_event_dedupe_unique'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'processed', 'failed'])), name='domain_event_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_key', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('secrets_token', models.TextField(blank=True)),
                ('secret_hints', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('unconfigured', 'پیکربندی نشده'), ('ok', 'متصل'), ('error', 'خطا'), ('disabled', 'غیرفعال')], default='unconfigured', max_length=20)),
                ('last_health_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider_key', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InboundWebhookReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.CharField(blank=True, max_length=200)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='integrations.integration')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'ورودی'), ('outbound', 'خروجی'), ('internal', 'داخلی')], max_length=10)),
                ('event_type', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('ok', 'موفق'), ('error', 'خطا'), ('skipped', 'نادیده')], max_length=10)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='integrations.integration')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=500)),
                ('event_types', models.JSONField(blank=True, default=list)),
                ('secret_token', models.TextField()),
                ('secret_hint', models.CharField(blank=True, max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در صف'), ('delivered', 'تحویل\u200cشده'), ('failed', 'ناموفق')], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(db_index=True)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.domainevent')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.webhooksubscription')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('prefix', models.CharField(max_length=16)),
                ('scopes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='api_token_name_nonblank')],
            },
        ),
        migrations.AddConstraint(
            model_name='integration',
            constraint=models.UniqueConstraint(fields=('provider_key', 'name'), name='integration_provider_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='integration',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['unconfigured', 'ok', 'error', 'disabled'])), name='integration_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='integration',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='integration_name_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='inboundwebhookreceipt',
            constraint=models.UniqueConstraint(fields=('integration', 'idempotency_key'), name='inbound_webhook_receipt_unique'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['integration', '-created_at'], name='integration_log_recent'),
        ),
        migrations.AddConstraint(
            model_name='webhooksubscription',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='webhook_subscription_name_nonblank'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='webhook_delivery_due'),
        ),
        migrations.AddConstraint(
            model_name='webhookdelivery',
            constraint=models.UniqueConstraint(fields=('subscription', 'event'), name='webhook_delivery_once'),
        ),
        migrations.AddConstraint(
            model_name='webhookdelivery',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'delivered', 'failed'])), name='webhook_delivery_status_valid'),
        ),
    ]
