# Generated by Django 5.2.17 on 2026-09-03 15:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aftersales', '0001_after_sales_foundation'),
        ('billing', '0013_invoice_document_date'),
        ('sales', '0019_customer_economic_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('content', models.BinaryField()),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('after_sales_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='aftersales.aftersalesrequest')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='sales.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='billing.invoice')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='sales.lead')),
                ('sales_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='sales.salesdocument')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
                'indexes': [models.Index(fields=['customer', '-uploaded_at'], name='attachments_custome_768c0f_idx'), models.Index(fields=['lead', '-uploaded_at'], name='attachments_lead_id_c1d2bc_idx'), models.Index(fields=['invoice', '-uploaded_at'], name='attachments_invoice_54a59a_idx'), models.Index(fields=['sales_document', '-uploaded_at'], name='attachments_sales_d_e355e0_idx'), models.Index(fields=['after_sales_request', '-uploaded_at'], name='attachments_after_s_849108_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('after_sales_request__isnull', True), ('customer__isnull', False), ('invoice__isnull', True), ('lead__isnull', True), ('sales_document__isnull', True)), models.Q(('after_sales_request__isnull', True), ('customer__isnull', True), ('invoice__isnull', True), ('lead__isnull', False), ('sales_document__isnull', True)), models.Q(('after_sales_request__isnull', True), ('customer__isnull', True), ('invoice__isnull', False), ('lead__isnull', True), ('sales_document__isnull', True)), models.Q(('after_sales_request__isnull', True), ('customer__isnull', True), ('invoice__isnull', True), ('lead__isnull', True), ('sales_document__isnull', False)), models.Q(('after_sales_request__isnull', False), ('customer__isnull', True), ('invoice__isnull', True), ('lead__isnull', True), ('sales_document__isnull', True)), _connector='OR'), name='attachment_exactly_one_parent'), models.CheckConstraint(condition=models.Q(('content_type__in', ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'])), name='attachment_content_type_allowed'), models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0), ('size_bytes__lte', 10485760)), name='attachment_size_within_default_limit'), models.CheckConstraint(condition=models.Q(('original_filename__regex', '\\S')), name='attachment_filename_nonblank')],
            },
        ),
    ]
