# Generated by Django 5.2.17 on 2026-08-09 00:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_add_money_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['confirmed', 'cancelled'])), name='sale_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('product__isnull', True), ('unit_price_snapshot__isnull', False), _connector='OR'), name='sale_product_has_price_snapshot'),
        ),
    ]
