# Generated by Django 5.2.17 on 2026-08-09 00:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_add_sale_state_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_at__isnull', True), ('assigned_by__isnull', True), ('assigned_to__isnull', True)), models.Q(('assigned_at__isnull', False), ('assigned_by__isnull', False), ('assigned_to__isnull', False)), _connector='OR'), name='lead_assignment_fields_consistent'),
        ),
    ]
