# Generated by Django 5.2.17 on 2026-08-12 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_customer_profile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_number', models.CharField(max_length=64, unique=True)),
                ('province_snapshot', models.CharField(blank=True, max_length=100)),
                ('city_snapshot', models.CharField(blank=True, max_length=100)),
                ('postal_code_snapshot', models.CharField(blank=True, max_length=32)),
                ('address_snapshot', models.CharField(blank=True, max_length=2000)),
                ('postal_status', models.CharField(db_index=True, max_length=80)),
                ('registered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.CharField(blank=True, max_length=4000)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_documents', to='sales.customer')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_sales_documents', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_documents', to='sales.sale')),
            ],
            options={
                'ordering': ['-registered_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PostalStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=80)),
                ('to_status', models.CharField(max_length=80)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postal_status_changes', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postal_history', to='sales.salesdocument')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='salesdocument',
            index=models.Index(fields=['customer', '-registered_at'], name='sales_sales_custome_5ec591_idx'),
        ),
        migrations.AddIndex(
            model_name='salesdocument',
            index=models.Index(fields=['province_snapshot', 'city_snapshot', '-registered_at'], name='sales_sales_provinc_c573f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesdocument',
            constraint=models.CheckConstraint(condition=models.Q(('document_number__regex', '\\S')), name='sales_document_number_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='salesdocument',
            constraint=models.CheckConstraint(condition=models.Q(('postal_status__regex', '\\S')), name='sales_document_postal_status_nonblank'),
        ),
        migrations.AddIndex(
            model_name='postalstatushistory',
            index=models.Index(fields=['document', '-changed_at'], name='sales_posta_documen_5a13f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='postalstatushistory',
            constraint=models.CheckConstraint(condition=models.Q(('to_status__regex', '\\S')), name='postal_history_to_status_nonblank'),
        ),
    ]
