# Generated by Django 5.2.17 on 2026-08-18 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_product_barcode_product_brand_productcategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='sales.customer'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'در انتظار تکمیل'), ('completed', 'تکمیل'), ('cancelled', 'کنسل شده')], db_index=True, default='pending', max_length=40),
        ),
        migrations.CreateModel(
            name='TargetAudienceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('raw_phone', models.CharField(max_length=40)),
                ('normalized_phone', models.CharField(db_index=True, editable=False, max_length=20)),
                ('status', models.CharField(choices=[('lead', 'سرنخ'), ('engaged', 'در تعامل'), ('customer', 'مشتری'), ('failed', 'ناموفق')], db_index=True, default='lead', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=4000)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_target_members', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_audience_entries', to='sales.customer')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_audience', to='sales.lead')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_target_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='interaction',
            name='target_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='sales.targetaudiencemember'),
        ),
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.CheckConstraint(condition=models.Q(('customer__isnull', False), ('target_member__isnull', False), _connector='OR'), name='interaction_names_someone'),
        ),
        migrations.AddIndex(
            model_name='targetaudiencemember',
            index=models.Index(fields=['lead', 'status', 'full_name'], name='sales_targe_lead_id_f3e765_idx'),
        ),
        migrations.AddIndex(
            model_name='targetaudiencemember',
            index=models.Index(fields=['normalized_phone', 'status'], name='sales_targe_normali_202a4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='targetaudiencemember',
            constraint=models.CheckConstraint(condition=models.Q(('full_name__regex', '\\S')), name='target_member_name_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='targetaudiencemember',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_phone__regex', '\\A\\+98[1-9][0-9]{9}\\Z')), name='target_member_phone_shape'),
        ),
        migrations.AddConstraint(
            model_name='targetaudiencemember',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['lead', 'engaged', 'customer', 'failed'])), name='target_member_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='targetaudiencemember',
            constraint=models.UniqueConstraint(fields=('lead', 'normalized_phone'), name='uniq_target_member_per_lead'),
        ),
    ]
