# Generated by Django 5.2.17 on 2026-08-18 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_interaction_customer_alter_lead_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='targetaudiencemember',
            name='uniq_target_member_per_lead',
        ),
        migrations.AddConstraint(
            model_name='targetaudiencemember',
            constraint=models.UniqueConstraint(fields=('normalized_phone',), name='uniq_target_member_phone'),
        ),
    ]
