# Generated by Django 5.2.17 on 2026-08-18 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_remove_targetaudiencemember_uniq_target_member_per_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='sales.customer'),
        ),
    ]
