# Generated by Django 5.2.17 on 2026-08-24 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_lead_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('box', 'جعبه'), ('piece', 'عدد'), ('carton', 'کارتن'), ('kilogram', 'کیلوگرم'), ('gram', 'گرم')], default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('unit__in', ['', 'box', 'piece', 'carton', 'kilogram', 'gram'])), name='product_unit_valid'),
        ),
    ]
