# Generated by Django 5.2.17 on 2026-08-25 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_product_unit_product_product_unit_valid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='kind',
            field=models.CharField(choices=[('individual', 'حقیقی'), ('legal', 'حقوقی')], db_index=True, default='individual', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['individual', 'legal'])), name='customer_kind_valid'),
        ),
    ]
