# Generated by Django 5.2.17 on 2026-08-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_customer_kind_customer_customer_kind_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='economic_code',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
