# Generated by Django 5.2.17 on 2026-09-21 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_customer_customer_province_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProviderSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('base_url', models.CharField(blank=True, max_length=500)),
                ('api_key_header', models.CharField(blank=True, default='X-API-Key', max_length=80)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('sender_account_code', models.CharField(blank=True, max_length=120)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=10)),
                ('test_url', models.CharField(blank=True, max_length=500)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'post provider settings',
                'verbose_name_plural': 'post provider settings',
            },
        ),
    ]
