# Generated by Django 5.2.17 on 2026-09-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_postprovidersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
