# Generated by Django 5.2.17 on 2026-09-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_person_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='normalized_phone',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=20),
        ),
    ]
