# Generated by Django 5.2.17 on 2026-09-29 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_backfill_interaction_normalized_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EbazarProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ebazar_product_id', models.CharField(max_length=40)),
                ('unit_weight_grams', models.PositiveIntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ebazar_link', to='sales.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostalShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.CharField(default='ebazar', max_length=30)),
                ('parcel_code', models.CharField(blank=True, db_index=True, max_length=40)),
                ('shenase', models.CharField(blank=True, max_length=40)),
                ('service_type', models.PositiveSmallIntegerField()),
                ('pay_type', models.PositiveSmallIntegerField()),
                ('city_id', models.PositiveIntegerField()),
                ('weight_grams', models.PositiveIntegerField()),
                ('goods_price_rial', models.BigIntegerField()),
                ('shipping_cost_rial', models.BigIntegerField(blank=True, null=True)),
                ('shipping_tax_rial', models.BigIntegerField(blank=True, null=True)),
                ('carrier_status_code', models.SmallIntegerField(blank=True, null=True)),
                ('carrier_status_text', models.CharField(blank=True, max_length=200)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postal_shipments', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='sales.salesdocument')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['document', '-created_at'], name='sales_posta_documen_a599a8_idx')],
            },
        ),
    ]
