# Generated by Django 5.2.17 on 2026-10-02 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_backfill_customer_owner_and_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['owner', 'is_active', '-created_at'], name='customer_owner_active_idx'),
        ),
    ]
