# Generated by Django 5.2.17 on 2026-10-02 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_payment_allocation_repeatable'),
        ('sales', '0028_customer_owner_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('normalized_name', models.CharField(editable=False, max_length=120, unique=True)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('paused', 'متوقف'), ('finished', 'تمام\u200cشده'), ('archived', 'بایگانی')], db_index=True, default='draft', max_length=16)),
                ('channel', models.CharField(choices=[('phone', 'تماس تلفنی'), ('sms', 'پیامک'), ('social', 'شبکه\u200cهای اجتماعی'), ('exhibition', 'نمایشگاه'), ('referral', 'معرفی'), ('website', 'وب\u200cسایت'), ('other', 'سایر')], default='phone', max_length=16)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('target_count', models.PositiveIntegerField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('system_key', models.CharField(blank=True, default='', max_length=16)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CampaignAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('auto', 'خودکار'), ('manual', 'دستی')], default='auto', max_length=8)),
                ('reason', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignAttributionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=8)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='targetaudiencemember',
            name='uniq_target_member_phone',
        ),
        migrations.AddField(
            model_name='targetaudiencemember',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetaudiencemember',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='targetaudiencemember',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_campaign_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='targetaudiencemember',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetaudiencemember',
            name='lost_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='targetaudiencemember',
            name='next_follow_up_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='targetaudiencemember',
            name='stage',
            field=models.CharField(choices=[('new', 'جدید'), ('contacted', 'تماس گرفته\u200cشده'), ('engaged', 'در تعامل'), ('converted', 'تبدیل\u200cشده'), ('lost', 'ازدست\u200cرفته')], db_index=True, default='new', max_length=12),
        ),
        migrations.AddField(
            model_name='targetaudiencemember',
            name='was_customer_on_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='responsibles',
            field=models.ManyToManyField(blank=True, related_name='responsible_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='sales.campaign'),
        ),
        migrations.AddField(
            model_name='targetaudiencemember',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='sales.campaign'),
        ),
        migrations.AddIndex(
            model_name='targetaudiencemember',
            index=models.Index(fields=['campaign', 'stage'], name='member_campaign_stage_idx'),
        ),
        migrations.AddConstraint(
            model_name='targetaudiencemember',
            constraint=models.UniqueConstraint(fields=('campaign', 'normalized_phone'), name='uniq_member_campaign_phone'),
        ),
        migrations.AddConstraint(
            model_name='targetaudiencemember',
            constraint=models.CheckConstraint(condition=models.Q(('stage__in', ['new', 'contacted', 'engaged', 'converted', 'lost'])), name='target_member_stage_valid'),
        ),
        migrations.AddField(
            model_name='campaignattribution',
            name='attributed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_attributions_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignattribution',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributions', to='sales.campaign'),
        ),
        migrations.AddField(
            model_name='campaignattribution',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_attribution', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='campaignattribution',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions', to='sales.targetaudiencemember'),
        ),
        migrations.AddField(
            model_name='campaignattributionlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignattributionlog',
            name='from_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sales.campaign'),
        ),
        migrations.AddField(
            model_name='campaignattributionlog',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_attribution_log', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='campaignattributionlog',
            name='to_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sales.campaign'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', '-created_at'], name='sales_campa_status_2cfa26_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='campaign_name_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'active', 'paused', 'finished', 'archived'])), name='campaign_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('starts_on__isnull', True), ('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='campaign_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(condition=models.Q(('system_key', ''), _negated=True), fields=('system_key',), name='uniq_campaign_system_key'),
        ),
        migrations.AddIndex(
            model_name='campaignattribution',
            index=models.Index(fields=['campaign', '-created_at'], name='sales_campa_campaig_60de62_idx'),
        ),
    ]
