# Generated by Django 5.2.17 on 2026-10-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_campaign_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetaudiencemember',
            name='was_customer_on_entry',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
