# Generated by Django 5.2.17 on 2026-10-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_member_entry_unknown'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='other_channels',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
