# Generated by Django 5.2.17 on 2026-09-27 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedid', models.CharField(max_length=64)),
                ('direction', models.CharField(choices=[('inbound', 'ورودی'), ('outbound', 'خروجی'), ('internal', 'داخلی')], max_length=10)),
                ('caller_raw', models.CharField(blank=True, max_length=64)),
                ('callee_raw', models.CharField(blank=True, max_length=64)),
                ('external_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('person_type', models.CharField(blank=True, max_length=32)),
                ('person_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ringing', 'در حال زنگ'), ('answered', 'در حال مکالمه'), ('completed', 'انجام\u200cشده'), ('missed', 'بی\u200cپاسخ'), ('no_answer', 'پاسخ داده نشد'), ('busy', 'مشغول'), ('failed', 'ناموفق')], default='ringing', max_length=10)),
                ('started_at', models.DateTimeField()),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('billsec', models.PositiveIntegerField(default=0)),
                ('hangup_cause', models.CharField(blank=True, max_length=80)),
                ('recording', models.CharField(blank=True, max_length=500)),
                ('seen_by_ami', models.BooleanField(default=False)),
                ('seen_in_cdr', models.BooleanField(default=False)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='integrations.integration')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CallNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ringing', 'در حال زنگ'), ('missed', 'تماس بی\u200cپاسخ')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='telephony.call')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CdrSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursor', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cdr_state', to='integrations.integration')),
            ],
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extensions', to='integrations.integration')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['integration', 'number'],
            },
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['person_type', 'person_id', '-started_at'], name='call_person_recent'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['user', '-started_at'], name='call_user_recent'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['status', '-started_at'], name='call_status_recent'),
        ),
        migrations.AddConstraint(
            model_name='call',
            constraint=models.UniqueConstraint(fields=('integration', 'linkedid'), name='call_linkedid_unique'),
        ),
        migrations.AddConstraint(
            model_name='call',
            constraint=models.CheckConstraint(condition=models.Q(('direction__in', ['inbound', 'outbound', 'internal'])), name='call_direction_valid'),
        ),
        migrations.AddConstraint(
            model_name='call',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ringing', 'answered', 'completed', 'missed', 'no_answer', 'busy', 'failed'])), name='call_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='call',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('person_id__isnull', True), ('person_type', '')), models.Q(models.Q(('person_type', ''), _negated=True), ('person_id__isnull', False)), _connector='OR'), name='call_person_reference_complete'),
        ),
        migrations.AddIndex(
            model_name='callnotification',
            index=models.Index(fields=['user', 'dismissed_at', '-created_at'], name='call_notification_inbox'),
        ),
        migrations.AddConstraint(
            model_name='callnotification',
            constraint=models.UniqueConstraint(fields=('user', 'call', 'kind'), name='call_notification_once'),
        ),
        migrations.AddConstraint(
            model_name='extension',
            constraint=models.UniqueConstraint(fields=('integration', 'number'), name='extension_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='extension',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('user__isnull', False)), fields=('integration', 'user'), name='extension_one_active_per_user'),
        ),
        migrations.AddConstraint(
            model_name='extension',
            constraint=models.CheckConstraint(condition=models.Q(('number__regex', '^[0-9*#]{1,20}$')), name='extension_number_digits'),
        ),
    ]
