# Generated by Django 5.2.17 on 2026-09-27 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('telephony', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=20)),
                ('dial', models.CharField(max_length=32)),
                ('external_number', models.CharField(blank=True, max_length=20)),
                ('person_type', models.CharField(blank=True, max_length=32)),
                ('person_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'در صف'), ('sending', 'در حال ارسال'), ('sent', 'ارسال\u200cشده'), ('failed', 'ناموفق')], default='pending', max_length=10)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('call', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originate_request', to='telephony.call')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='originate_requests', to='integrations.integration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['integration', 'status', 'created_at'], name='originate_queue'), models.Index(fields=['user', '-created_at'], name='originate_by_user')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'sending', 'sent', 'failed'])), name='originate_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('person_id__isnull', True), ('person_type', '')), models.Q(models.Q(('person_type', ''), _negated=True), ('person_id__isnull', False)), _connector='OR'), name='originate_person_reference_complete')],
            },
        ),
    ]
